sqlConfig: &sqlConfig
  code: sqldb
  driverName: mysql
  urlAddress: "[username]:[password]@tcp([host]:[port])/[dbname]?charset=utf8"
  dbName:
zapConfig: &zapConfig
  code: zap
  level: debug
  enableCaller: true
logConfig: *zapConfig